---
- name: debian_security | allowing SSH password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication yes"
    state: present
  notify: restart ssh

- name: debian_security | disabling SSH GSS API authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^GSSAPIAuthentication"
    line: "GSSAPIAuthentication no"
    state: present
  notify: restart ssh
